# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Publish Docker image

on:
  workflow_dispatch:
  schedule:
    - cron: "5 3 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
    tags:
      - "*"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: windows-2019
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Check if update available
        id: check
        uses: giggio/docker-image-update-checker@v2
        with:
          base-image: mcr.microsoft.com/windows/servercore:ltsc2019
          image: lambda3/notifypasswordexpiration:latest
          os: windows
          verbose: true

      - name: Extract metadata (tags, labels) for Docker
        id: meta_latest
        uses: docker/metadata-action@v3
        with:
          images: lambda3/notifypasswordexpiration
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=tag
        if: steps.check.outputs.needs-updating == 'true'

      - name: Build and push
        working-directory: .
        run: |
          docker login -u $env:DOCKER_USERNAME -p $env:DOCKER_PASSWORD
          Invoke-Expression "docker build --pull $($env:TAGS.Split("`n") | % { '-t "' + $_ + '"' }) $($env:LABELS.Split("`n") | % { '--label "' + $_ + '"' }) ."
          $($env:TAGS.Split("`n") | % { docker push $_ })
          docker logout
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          TAGS: ${{ steps.meta_latest.outputs.tags }}
          LABELS: ${{ steps.meta_latest.outputs.labels }}
        if: steps.check.outputs.needs-updating == 'true'
